name: InventoryAI
options:
  minimumXcodeGenVersion: 2.44.0
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "18.0"
settings:
  base:
    SWIFT_VERSION: "5.10"
    TARGETED_DEVICE_FAMILY: "1"
    DEVELOPMENT_TEAM: ""
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 6.0.0
targets:
  InventoryAI:
    type: application
    platform: iOS
    sources:
      - path: ios/App
      - path: ios/Features
      - path: ios/Models
      - path: ios/Persistence
      - path: ios/Repositories
      - path: ios/Services
      - path: ios/UseCases
      - path: ios/Shared
    dependencies:
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.projectvay.inventoryai
        PRODUCT_NAME: InventoryAI
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGNING_ALLOWED: NO
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Домашний Инвентарь"
        INFOPLIST_KEY_LSRequiresIPhoneOS: YES
        INFOPLIST_KEY_NSCameraUsageDescription: "Камера нужна для сканирования штрихкодов продуктов."
        INFOPLIST_KEY_BarcodeProxyBaseURL: ""
        INFOPLIST_KEY_EANDBApiKey: ""
        INFOPLIST_KEY_EnableEANDBLookup: NO
        INFOPLIST_KEY_EnableRFLookup: NO
        INFOPLIST_KEY_EnableOpenFoodFactsLookup: YES
        INFOPLIST_KEY_AllowInsecureLookupEndpoints: NO
        INFOPLIST_KEY_RecipeServiceBaseURL: "http://127.0.0.1:8080"
        INFOPLIST_KEY_AllowInsecureRecipeServiceURL: YES
        INFOPLIST_KEY_LookupTimeoutSeconds: "3.0"
        INFOPLIST_KEY_LookupRetryCount: "2"
        INFOPLIST_KEY_LookupRetryDelayMilliseconds: "350"
        INFOPLIST_KEY_LookupProviderCooldownMilliseconds: "250"
        INFOPLIST_KEY_LookupCircuitBreakerFailureThreshold: "3"
        INFOPLIST_KEY_LookupCircuitBreakerCooldownSeconds: "60"
        INFOPLIST_KEY_LookupNegativeCacheSeconds: "180"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        SUPPORTS_MACCATALYST: NO
schemes:
  InventoryAI:
    build:
      targets:
        InventoryAI: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
