name: InventoryAI
options:
  createIntermediateGroups: true
  minimumXcodeGenVersion: 2.38.0
  xcodeVersion: "26.2"

settings:
  base:
    SWIFT_VERSION: 5.10
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: "1"
    IPHONEOS_DEPLOYMENT_TARGET: 26.0

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 6.0.0
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: 12.8.0

targets:
  InventoryCore:
    type: framework
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Models
      - path: Persistence
      - path: Repositories
      - path: Services
      - path: Shared
      - path: UseCases
    dependencies:
      - package: GRDB
        product: GRDB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.projectvay.inventorycore
        PRODUCT_NAME: InventoryCore
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic

  InventoryCoreTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Tests/InventoryCoreTests
    dependencies:
      - target: InventoryCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.projectvay.inventorycore.tests
        PRODUCT_NAME: InventoryCoreTests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic

  InventoryAI:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: App
      - path: Features
      - path: Models
      - path: Persistence
      - path: Repositories
      - path: Services
      - path: Shared
      - path: UseCases
      - path: Assets.xcassets
    dependencies:
      - package: GRDB
        product: GRDB
      - package: Nuke
        product: Nuke
      - package: Nuke
        product: NukeUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.projectvay.inventoryai
        PRODUCT_NAME: InventoryAI
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: ДомИнвентарь
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.food-and-drink
        INFOPLIST_KEY_NSHealthShareUsageDescription: Нужно для чтения веса, жира и КБЖУ из Apple Health.
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: Нужно для синхронизации данных питания и прогресса.
        INFOPLIST_KEY_NSCameraUsageDescription: Камера нужна для сканирования штрихкодов и DataMatrix.
        INFOPLIST_KEY_NSSiriUsageDescription: "Siri поможет быстро добавлять продукты и проверять сроки годности."
        INFOPLIST_KEY_NSAppTransportSecurity_NSAllowsLocalNetworking: YES
        INFOPLIST_KEY_NSAppTransportSecurity_NSExceptionDomains_localhost_NSExceptionAllowsInsecureHTTPLoads: YES
        INFOPLIST_KEY_NSAppTransportSecurity_NSExceptionDomains_localhost_NSIncludesSubdomains: YES
        INFOPLIST_KEY_NSAppTransportSecurity_NSExceptionDomains_127.0.0.1_NSExceptionAllowsInsecureHTTPLoads: YES
        INFOPLIST_KEY_NSAppTransportSecurity_NSExceptionDomains_127.0.0.1_NSIncludesSubdomains: YES
        INFOPLIST_KEY_RecipeServiceBaseURL: "http://127.0.0.1:8080"
        INFOPLIST_KEY_AllowInsecureRecipeServiceURL: YES
        INFOPLIST_KEY_AllowInsecureLookupEndpoints: YES
        INFOPLIST_KEY_BarcodeProxyBaseURL: "http://127.0.0.1:8080/api/v1"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SUPPORTS_MACCATALYST: NO
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: App/InventoryAI.entitlements
        Release:
          CODE_SIGN_ENTITLEMENTS: App/InventoryAI.entitlements

schemes:
  InventoryAI:
    build:
      targets:
        InventoryAI: all
    test:
      targets:
        - InventoryCoreTests

  InventoryCore:
    build:
      targets:
        InventoryCore: all
    test:
      targets:
        - InventoryCoreTests
